version: "3"
services:
  redis:
    container_name: redis
    privileged: true
    image: redis
    ports:
      - 6379:6379
    volumes:
      - /usr/local/docker/redis/conf/redis.conf:/etc/redis/redis.conf
      - /usr/local/docker/redis/data:/data
    command: 
      redis-server /etc/redis/redis.conf --appendonly yes
  rabbitmq:
     container_name: rabbitmq
     hostname: my-rabbit
     image: rabbitmq:management
     ports:
       - 5672:5672
       - 15672:15672
  nexus3:
    container_name: nexus3
    privileged: true
    image: docker.io/sonatype/nexus3
    ports:
       - 8081:8081
       - 8082:8082
       - 8083:8083
       - 8084:8084
       - 8085:8085
    volumes:
      - /usr/local/docker/nexus3/nexus-data:/nexus-data
  mongodb: 
    container_name: mongodb
    privileged: true
    image: mongo
    ports:
      - 27017:27017
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /usr/local/docker/mongo/config:/data/configdb
      - /usr/local/docker/mongo/data:/data/db
    command:
      --auth
  mysql:
    container_name: mysql
    privileged: true
    image: mysql
    ports:
       - 3306:3306
    volumes:
      - /usr/local/docker/mysql/conf:/etc/mysql/conf.d
      - /usr/local/docker/mysql/logs:/logs
      - /usr/local/docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
  nginx:
    container_name: nginx
    privileged: true
    image: nginx
    ports:
       - 8080:80
    volumes:
      - /usr/local/docker/nginx/conf:/etc/nginx/conf.d
      - /usr/local/docker/nginx/logs:/var/log/nginx
  ftp:
    container_name: ftp
    privileged: true
    image: fauria/vsftpd
    ports:
       - 20:20
       - 21:21
       - 21100-21110:21100-21110
    volumes:
      - /usr/local/docker/vsftpd:/home/vsftpd
    environment:
      - FTP_USER=ygo
      - FTP_PASS=ygo
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.1.1
    network_mode: esnetwork
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes:
      - /usr/local/docker/es/config/elasticsearch.yml:/config/elasticsearch.yml
      - /usr/local/docker/es/plugins:/plugins
      - /usr/local/docker/es/data:/data
      - /usr/local/docker/es/logs:/logs
  kibana:
    container_name: kibana
    image: kibana:7.1.1
    network_mode: esnetwork
    ports:
      - 5601:5601
  elasticsearch-head:
    container_name: elasticsearch-head
    image: mobz/elasticsearch-head:5
    ports:
      - 9100:9100
  logstash:
    container_name: logstash
    privileged: true
    network_mode: esnetwork
    image: logstash:7.1.1
    ports:
      - 5044:5044
    volumes:
      - /usr/local/docker/logstash/log/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /usr/local/docker/logstash/config/conf.d/:/usr/share/logstash/conf.d/