server:
  port: 9200
  
spring:
  application:    
    name: gateway

eureka:  
  instance:
    prefer-ip-address: true
  client:    
    serviceUrl:
      defaultZone: http://ygo:ygo@127.0.0.1:9000/eureka/
    registerWithEureka: true