// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: package.proto

package cn.mayu.yugioh.common.dto.transform;

public final class PackageProto {
  private PackageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PackageDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.mayu.yugioh.common.dto.cardsource.PackageDetail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string packageName = 1;</code>
     *
     * <pre>
     * 卡包名称
     * </pre>
     */
    boolean hasPackageName();
    /**
     * <code>optional string packageName = 1;</code>
     *
     * <pre>
     * 卡包名称
     * </pre>
     */
    java.lang.String getPackageName();
    /**
     * <code>optional string packageName = 1;</code>
     *
     * <pre>
     * 卡包名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getPackageNameBytes();

    /**
     * <code>optional string offeringDate = 2;</code>
     *
     * <pre>
     * 卡包发售时间
     * </pre>
     */
    boolean hasOfferingDate();
    /**
     * <code>optional string offeringDate = 2;</code>
     *
     * <pre>
     * 卡包发售时间
     * </pre>
     */
    java.lang.String getOfferingDate();
    /**
     * <code>optional string offeringDate = 2;</code>
     *
     * <pre>
     * 卡包发售时间
     * </pre>
     */
    com.google.protobuf.ByteString
        getOfferingDateBytes();

    /**
     * <code>optional int32 cardCount = 3;</code>
     *
     * <pre>
     * 卡片总数
     * </pre>
     */
    boolean hasCardCount();
    /**
     * <code>optional int32 cardCount = 3;</code>
     *
     * <pre>
     * 卡片总数
     * </pre>
     */
    int getCardCount();

    /**
     * <code>optional string abbreviate = 4;</code>
     *
     * <pre>
     * 卡包缩写
     * </pre>
     */
    boolean hasAbbreviate();
    /**
     * <code>optional string abbreviate = 4;</code>
     *
     * <pre>
     * 卡包缩写
     * </pre>
     */
    java.lang.String getAbbreviate();
    /**
     * <code>optional string abbreviate = 4;</code>
     *
     * <pre>
     * 卡包缩写
     * </pre>
     */
    com.google.protobuf.ByteString
        getAbbreviateBytes();

    /**
     * <code>optional string packageImg = 5;</code>
     *
     * <pre>
     * 卡包图片
     * </pre>
     */
    boolean hasPackageImg();
    /**
     * <code>optional string packageImg = 5;</code>
     *
     * <pre>
     * 卡包图片
     * </pre>
     */
    java.lang.String getPackageImg();
    /**
     * <code>optional string packageImg = 5;</code>
     *
     * <pre>
     * 卡包图片
     * </pre>
     */
    com.google.protobuf.ByteString
        getPackageImgBytes();

    /**
     * <code>optional string coverImg = 6;</code>
     *
     * <pre>
     * 卡包封面
     * </pre>
     */
    boolean hasCoverImg();
    /**
     * <code>optional string coverImg = 6;</code>
     *
     * <pre>
     * 卡包封面
     * </pre>
     */
    java.lang.String getCoverImg();
    /**
     * <code>optional string coverImg = 6;</code>
     *
     * <pre>
     * 卡包封面
     * </pre>
     */
    com.google.protobuf.ByteString
        getCoverImgBytes();

    /**
     * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
     *
     * <pre>
     * 卡片详情
     * </pre>
     */
    java.util.List<cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail>
        getCardsList();
    /**
     * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
     *
     * <pre>
     * 卡片详情
     * </pre>
     */
    cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail getCards(int index);
    /**
     * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
     *
     * <pre>
     * 卡片详情
     * </pre>
     */
    int getCardsCount();
    /**
     * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
     *
     * <pre>
     * 卡片详情
     * </pre>
     */
    java.util.List<? extends cn.mayu.yugioh.common.dto.transform.CardProto.CardDetailOrBuilder>
        getCardsOrBuilderList();
    /**
     * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
     *
     * <pre>
     * 卡片详情
     * </pre>
     */
    cn.mayu.yugioh.common.dto.transform.CardProto.CardDetailOrBuilder getCardsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cn.mayu.yugioh.common.dto.cardsource.PackageDetail}
   */
  public static final class PackageDetail extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cn.mayu.yugioh.common.dto.cardsource.PackageDetail)
      PackageDetailOrBuilder {
    // Use PackageDetail.newBuilder() to construct.
    private PackageDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PackageDetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PackageDetail defaultInstance;
    public static PackageDetail getDefaultInstance() {
      return defaultInstance;
    }

    public PackageDetail getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PackageDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              packageName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              offeringDate_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              cardCount_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              abbreviate_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              packageImg_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              coverImg_ = bs;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                cards_ = new java.util.ArrayList<cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail>();
                mutable_bitField0_ |= 0x00000040;
              }
              cards_.add(input.readMessage(cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          cards_ = java.util.Collections.unmodifiableList(cards_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.mayu.yugioh.common.dto.transform.PackageProto.internal_static_cn_mayu_yugioh_common_dto_cardsource_PackageDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.mayu.yugioh.common.dto.transform.PackageProto.internal_static_cn_mayu_yugioh_common_dto_cardsource_PackageDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail.class, cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail.Builder.class);
    }

    public static com.google.protobuf.Parser<PackageDetail> PARSER =
        new com.google.protobuf.AbstractParser<PackageDetail>() {
      public PackageDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PackageDetail(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PackageDetail> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PACKAGENAME_FIELD_NUMBER = 1;
    private java.lang.Object packageName_;
    /**
     * <code>optional string packageName = 1;</code>
     *
     * <pre>
     * 卡包名称
     * </pre>
     */
    public boolean hasPackageName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string packageName = 1;</code>
     *
     * <pre>
     * 卡包名称
     * </pre>
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          packageName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string packageName = 1;</code>
     *
     * <pre>
     * 卡包名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OFFERINGDATE_FIELD_NUMBER = 2;
    private java.lang.Object offeringDate_;
    /**
     * <code>optional string offeringDate = 2;</code>
     *
     * <pre>
     * 卡包发售时间
     * </pre>
     */
    public boolean hasOfferingDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string offeringDate = 2;</code>
     *
     * <pre>
     * 卡包发售时间
     * </pre>
     */
    public java.lang.String getOfferingDate() {
      java.lang.Object ref = offeringDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          offeringDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string offeringDate = 2;</code>
     *
     * <pre>
     * 卡包发售时间
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOfferingDateBytes() {
      java.lang.Object ref = offeringDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        offeringDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARDCOUNT_FIELD_NUMBER = 3;
    private int cardCount_;
    /**
     * <code>optional int32 cardCount = 3;</code>
     *
     * <pre>
     * 卡片总数
     * </pre>
     */
    public boolean hasCardCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 cardCount = 3;</code>
     *
     * <pre>
     * 卡片总数
     * </pre>
     */
    public int getCardCount() {
      return cardCount_;
    }

    public static final int ABBREVIATE_FIELD_NUMBER = 4;
    private java.lang.Object abbreviate_;
    /**
     * <code>optional string abbreviate = 4;</code>
     *
     * <pre>
     * 卡包缩写
     * </pre>
     */
    public boolean hasAbbreviate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string abbreviate = 4;</code>
     *
     * <pre>
     * 卡包缩写
     * </pre>
     */
    public java.lang.String getAbbreviate() {
      java.lang.Object ref = abbreviate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          abbreviate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string abbreviate = 4;</code>
     *
     * <pre>
     * 卡包缩写
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAbbreviateBytes() {
      java.lang.Object ref = abbreviate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        abbreviate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACKAGEIMG_FIELD_NUMBER = 5;
    private java.lang.Object packageImg_;
    /**
     * <code>optional string packageImg = 5;</code>
     *
     * <pre>
     * 卡包图片
     * </pre>
     */
    public boolean hasPackageImg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string packageImg = 5;</code>
     *
     * <pre>
     * 卡包图片
     * </pre>
     */
    public java.lang.String getPackageImg() {
      java.lang.Object ref = packageImg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          packageImg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string packageImg = 5;</code>
     *
     * <pre>
     * 卡包图片
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPackageImgBytes() {
      java.lang.Object ref = packageImg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageImg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COVERIMG_FIELD_NUMBER = 6;
    private java.lang.Object coverImg_;
    /**
     * <code>optional string coverImg = 6;</code>
     *
     * <pre>
     * 卡包封面
     * </pre>
     */
    public boolean hasCoverImg() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string coverImg = 6;</code>
     *
     * <pre>
     * 卡包封面
     * </pre>
     */
    public java.lang.String getCoverImg() {
      java.lang.Object ref = coverImg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          coverImg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string coverImg = 6;</code>
     *
     * <pre>
     * 卡包封面
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCoverImgBytes() {
      java.lang.Object ref = coverImg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        coverImg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARDS_FIELD_NUMBER = 7;
    private java.util.List<cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail> cards_;
    /**
     * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
     *
     * <pre>
     * 卡片详情
     * </pre>
     */
    public java.util.List<cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail> getCardsList() {
      return cards_;
    }
    /**
     * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
     *
     * <pre>
     * 卡片详情
     * </pre>
     */
    public java.util.List<? extends cn.mayu.yugioh.common.dto.transform.CardProto.CardDetailOrBuilder>
        getCardsOrBuilderList() {
      return cards_;
    }
    /**
     * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
     *
     * <pre>
     * 卡片详情
     * </pre>
     */
    public int getCardsCount() {
      return cards_.size();
    }
    /**
     * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
     *
     * <pre>
     * 卡片详情
     * </pre>
     */
    public cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail getCards(int index) {
      return cards_.get(index);
    }
    /**
     * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
     *
     * <pre>
     * 卡片详情
     * </pre>
     */
    public cn.mayu.yugioh.common.dto.transform.CardProto.CardDetailOrBuilder getCardsOrBuilder(
        int index) {
      return cards_.get(index);
    }

    private void initFields() {
      packageName_ = "";
      offeringDate_ = "";
      cardCount_ = 0;
      abbreviate_ = "";
      packageImg_ = "";
      coverImg_ = "";
      cards_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPackageNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getOfferingDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, cardCount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAbbreviateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getPackageImgBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getCoverImgBytes());
      }
      for (int i = 0; i < cards_.size(); i++) {
        output.writeMessage(7, cards_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPackageNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getOfferingDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cardCount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAbbreviateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPackageImgBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getCoverImgBytes());
      }
      for (int i = 0; i < cards_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, cards_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.mayu.yugioh.common.dto.cardsource.PackageDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.mayu.yugioh.common.dto.cardsource.PackageDetail)
        cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.mayu.yugioh.common.dto.transform.PackageProto.internal_static_cn_mayu_yugioh_common_dto_cardsource_PackageDetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.mayu.yugioh.common.dto.transform.PackageProto.internal_static_cn_mayu_yugioh_common_dto_cardsource_PackageDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail.class, cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail.Builder.class);
      }

      // Construct using cn.mayu.yugioh.common.dto.cardsource.PackageProto.PackageDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCardsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        packageName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        offeringDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        cardCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        abbreviate_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        packageImg_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        coverImg_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        if (cardsBuilder_ == null) {
          cards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          cardsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.mayu.yugioh.common.dto.transform.PackageProto.internal_static_cn_mayu_yugioh_common_dto_cardsource_PackageDetail_descriptor;
      }

      public cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail getDefaultInstanceForType() {
        return cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail.getDefaultInstance();
      }

      public cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail build() {
        cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail buildPartial() {
        cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail result = new cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packageName_ = packageName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.offeringDate_ = offeringDate_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cardCount_ = cardCount_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.abbreviate_ = abbreviate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.packageImg_ = packageImg_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.coverImg_ = coverImg_;
        if (cardsBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            cards_ = java.util.Collections.unmodifiableList(cards_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.cards_ = cards_;
        } else {
          result.cards_ = cardsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail) {
          return mergeFrom((cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail other) {
        if (other == cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail.getDefaultInstance()) return this;
        if (other.hasPackageName()) {
          bitField0_ |= 0x00000001;
          packageName_ = other.packageName_;
          onChanged();
        }
        if (other.hasOfferingDate()) {
          bitField0_ |= 0x00000002;
          offeringDate_ = other.offeringDate_;
          onChanged();
        }
        if (other.hasCardCount()) {
          setCardCount(other.getCardCount());
        }
        if (other.hasAbbreviate()) {
          bitField0_ |= 0x00000008;
          abbreviate_ = other.abbreviate_;
          onChanged();
        }
        if (other.hasPackageImg()) {
          bitField0_ |= 0x00000010;
          packageImg_ = other.packageImg_;
          onChanged();
        }
        if (other.hasCoverImg()) {
          bitField0_ |= 0x00000020;
          coverImg_ = other.coverImg_;
          onChanged();
        }
        if (cardsBuilder_ == null) {
          if (!other.cards_.isEmpty()) {
            if (cards_.isEmpty()) {
              cards_ = other.cards_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureCardsIsMutable();
              cards_.addAll(other.cards_);
            }
            onChanged();
          }
        } else {
          if (!other.cards_.isEmpty()) {
            if (cardsBuilder_.isEmpty()) {
              cardsBuilder_.dispose();
              cardsBuilder_ = null;
              cards_ = other.cards_;
              bitField0_ = (bitField0_ & ~0x00000040);
              cardsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCardsFieldBuilder() : null;
            } else {
              cardsBuilder_.addAllMessages(other.cards_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.mayu.yugioh.common.dto.transform.PackageProto.PackageDetail) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object packageName_ = "";
      /**
       * <code>optional string packageName = 1;</code>
       *
       * <pre>
       * 卡包名称
       * </pre>
       */
      public boolean hasPackageName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string packageName = 1;</code>
       *
       * <pre>
       * 卡包名称
       * </pre>
       */
      public java.lang.String getPackageName() {
        java.lang.Object ref = packageName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            packageName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string packageName = 1;</code>
       *
       * <pre>
       * 卡包名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPackageNameBytes() {
        java.lang.Object ref = packageName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          packageName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string packageName = 1;</code>
       *
       * <pre>
       * 卡包名称
       * </pre>
       */
      public Builder setPackageName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        packageName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string packageName = 1;</code>
       *
       * <pre>
       * 卡包名称
       * </pre>
       */
      public Builder clearPackageName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packageName_ = getDefaultInstance().getPackageName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string packageName = 1;</code>
       *
       * <pre>
       * 卡包名称
       * </pre>
       */
      public Builder setPackageNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        packageName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object offeringDate_ = "";
      /**
       * <code>optional string offeringDate = 2;</code>
       *
       * <pre>
       * 卡包发售时间
       * </pre>
       */
      public boolean hasOfferingDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string offeringDate = 2;</code>
       *
       * <pre>
       * 卡包发售时间
       * </pre>
       */
      public java.lang.String getOfferingDate() {
        java.lang.Object ref = offeringDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            offeringDate_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string offeringDate = 2;</code>
       *
       * <pre>
       * 卡包发售时间
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOfferingDateBytes() {
        java.lang.Object ref = offeringDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          offeringDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string offeringDate = 2;</code>
       *
       * <pre>
       * 卡包发售时间
       * </pre>
       */
      public Builder setOfferingDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        offeringDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string offeringDate = 2;</code>
       *
       * <pre>
       * 卡包发售时间
       * </pre>
       */
      public Builder clearOfferingDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        offeringDate_ = getDefaultInstance().getOfferingDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string offeringDate = 2;</code>
       *
       * <pre>
       * 卡包发售时间
       * </pre>
       */
      public Builder setOfferingDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        offeringDate_ = value;
        onChanged();
        return this;
      }

      private int cardCount_ ;
      /**
       * <code>optional int32 cardCount = 3;</code>
       *
       * <pre>
       * 卡片总数
       * </pre>
       */
      public boolean hasCardCount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 cardCount = 3;</code>
       *
       * <pre>
       * 卡片总数
       * </pre>
       */
      public int getCardCount() {
        return cardCount_;
      }
      /**
       * <code>optional int32 cardCount = 3;</code>
       *
       * <pre>
       * 卡片总数
       * </pre>
       */
      public Builder setCardCount(int value) {
        bitField0_ |= 0x00000004;
        cardCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cardCount = 3;</code>
       *
       * <pre>
       * 卡片总数
       * </pre>
       */
      public Builder clearCardCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cardCount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object abbreviate_ = "";
      /**
       * <code>optional string abbreviate = 4;</code>
       *
       * <pre>
       * 卡包缩写
       * </pre>
       */
      public boolean hasAbbreviate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string abbreviate = 4;</code>
       *
       * <pre>
       * 卡包缩写
       * </pre>
       */
      public java.lang.String getAbbreviate() {
        java.lang.Object ref = abbreviate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            abbreviate_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string abbreviate = 4;</code>
       *
       * <pre>
       * 卡包缩写
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAbbreviateBytes() {
        java.lang.Object ref = abbreviate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          abbreviate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string abbreviate = 4;</code>
       *
       * <pre>
       * 卡包缩写
       * </pre>
       */
      public Builder setAbbreviate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        abbreviate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string abbreviate = 4;</code>
       *
       * <pre>
       * 卡包缩写
       * </pre>
       */
      public Builder clearAbbreviate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        abbreviate_ = getDefaultInstance().getAbbreviate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string abbreviate = 4;</code>
       *
       * <pre>
       * 卡包缩写
       * </pre>
       */
      public Builder setAbbreviateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        abbreviate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object packageImg_ = "";
      /**
       * <code>optional string packageImg = 5;</code>
       *
       * <pre>
       * 卡包图片
       * </pre>
       */
      public boolean hasPackageImg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string packageImg = 5;</code>
       *
       * <pre>
       * 卡包图片
       * </pre>
       */
      public java.lang.String getPackageImg() {
        java.lang.Object ref = packageImg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            packageImg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string packageImg = 5;</code>
       *
       * <pre>
       * 卡包图片
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPackageImgBytes() {
        java.lang.Object ref = packageImg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          packageImg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string packageImg = 5;</code>
       *
       * <pre>
       * 卡包图片
       * </pre>
       */
      public Builder setPackageImg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        packageImg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string packageImg = 5;</code>
       *
       * <pre>
       * 卡包图片
       * </pre>
       */
      public Builder clearPackageImg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        packageImg_ = getDefaultInstance().getPackageImg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string packageImg = 5;</code>
       *
       * <pre>
       * 卡包图片
       * </pre>
       */
      public Builder setPackageImgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        packageImg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object coverImg_ = "";
      /**
       * <code>optional string coverImg = 6;</code>
       *
       * <pre>
       * 卡包封面
       * </pre>
       */
      public boolean hasCoverImg() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string coverImg = 6;</code>
       *
       * <pre>
       * 卡包封面
       * </pre>
       */
      public java.lang.String getCoverImg() {
        java.lang.Object ref = coverImg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            coverImg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string coverImg = 6;</code>
       *
       * <pre>
       * 卡包封面
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCoverImgBytes() {
        java.lang.Object ref = coverImg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          coverImg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string coverImg = 6;</code>
       *
       * <pre>
       * 卡包封面
       * </pre>
       */
      public Builder setCoverImg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        coverImg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string coverImg = 6;</code>
       *
       * <pre>
       * 卡包封面
       * </pre>
       */
      public Builder clearCoverImg() {
        bitField0_ = (bitField0_ & ~0x00000020);
        coverImg_ = getDefaultInstance().getCoverImg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string coverImg = 6;</code>
       *
       * <pre>
       * 卡包封面
       * </pre>
       */
      public Builder setCoverImgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        coverImg_ = value;
        onChanged();
        return this;
      }

      private java.util.List<cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail> cards_ =
        java.util.Collections.emptyList();
      private void ensureCardsIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          cards_ = new java.util.ArrayList<cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail>(cards_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail, cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail.Builder, cn.mayu.yugioh.common.dto.transform.CardProto.CardDetailOrBuilder> cardsBuilder_;

      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public java.util.List<cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail> getCardsList() {
        if (cardsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cards_);
        } else {
          return cardsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public int getCardsCount() {
        if (cardsBuilder_ == null) {
          return cards_.size();
        } else {
          return cardsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail getCards(int index) {
        if (cardsBuilder_ == null) {
          return cards_.get(index);
        } else {
          return cardsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public Builder setCards(
          int index, cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail value) {
        if (cardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardsIsMutable();
          cards_.set(index, value);
          onChanged();
        } else {
          cardsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public Builder setCards(
          int index, cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail.Builder builderForValue) {
        if (cardsBuilder_ == null) {
          ensureCardsIsMutable();
          cards_.set(index, builderForValue.build());
          onChanged();
        } else {
          cardsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public Builder addCards(cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail value) {
        if (cardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardsIsMutable();
          cards_.add(value);
          onChanged();
        } else {
          cardsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public Builder addCards(
          int index, cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail value) {
        if (cardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardsIsMutable();
          cards_.add(index, value);
          onChanged();
        } else {
          cardsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public Builder addCards(
          cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail.Builder builderForValue) {
        if (cardsBuilder_ == null) {
          ensureCardsIsMutable();
          cards_.add(builderForValue.build());
          onChanged();
        } else {
          cardsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public Builder addCards(
          int index, cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail.Builder builderForValue) {
        if (cardsBuilder_ == null) {
          ensureCardsIsMutable();
          cards_.add(index, builderForValue.build());
          onChanged();
        } else {
          cardsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public Builder addAllCards(
          java.lang.Iterable<? extends cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail> values) {
        if (cardsBuilder_ == null) {
          ensureCardsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cards_);
          onChanged();
        } else {
          cardsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public Builder clearCards() {
        if (cardsBuilder_ == null) {
          cards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          cardsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public Builder removeCards(int index) {
        if (cardsBuilder_ == null) {
          ensureCardsIsMutable();
          cards_.remove(index);
          onChanged();
        } else {
          cardsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail.Builder getCardsBuilder(
          int index) {
        return getCardsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public cn.mayu.yugioh.common.dto.transform.CardProto.CardDetailOrBuilder getCardsOrBuilder(
          int index) {
        if (cardsBuilder_ == null) {
          return cards_.get(index);  } else {
          return cardsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public java.util.List<? extends cn.mayu.yugioh.common.dto.transform.CardProto.CardDetailOrBuilder>
           getCardsOrBuilderList() {
        if (cardsBuilder_ != null) {
          return cardsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cards_);
        }
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail.Builder addCardsBuilder() {
        return getCardsFieldBuilder().addBuilder(
            cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail.Builder addCardsBuilder(
          int index) {
        return getCardsFieldBuilder().addBuilder(
            index, cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.mayu.yugioh.common.dto.cardsource.CardDetail cards = 7;</code>
       *
       * <pre>
       * 卡片详情
       * </pre>
       */
      public java.util.List<cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail.Builder>
           getCardsBuilderList() {
        return getCardsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail, cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail.Builder, cn.mayu.yugioh.common.dto.transform.CardProto.CardDetailOrBuilder>
          getCardsFieldBuilder() {
        if (cardsBuilder_ == null) {
          cardsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail, cn.mayu.yugioh.common.dto.transform.CardProto.CardDetail.Builder, cn.mayu.yugioh.common.dto.transform.CardProto.CardDetailOrBuilder>(
                  cards_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          cards_ = null;
        }
        return cardsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:cn.mayu.yugioh.common.dto.cardsource.PackageDetail)
    }

    static {
      defaultInstance = new PackageDetail(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cn.mayu.yugioh.common.dto.cardsource.PackageDetail)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_mayu_yugioh_common_dto_cardsource_PackageDetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_mayu_yugioh_common_dto_cardsource_PackageDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpackage.proto\022$cn.mayu.yugioh.common.d" +
      "to.cardsource\032\ncard.proto\"\310\001\n\rPackageDet" +
      "ail\022\023\n\013packageName\030\001 \001(\t\022\024\n\014offeringDate" +
      "\030\002 \001(\t\022\021\n\tcardCount\030\003 \001(\005\022\022\n\nabbreviate\030" +
      "\004 \001(\t\022\022\n\npackageImg\030\005 \001(\t\022\020\n\010coverImg\030\006 " +
      "\001(\t\022?\n\005cards\030\007 \003(\01320.cn.mayu.yugioh.comm" +
      "on.dto.cardsource.CardDetailB\016B\014PackageP" +
      "roto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.mayu.yugioh.common.dto.transform.CardProto.getDescriptor(),
        }, assigner);
    internal_static_cn_mayu_yugioh_common_dto_cardsource_PackageDetail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_mayu_yugioh_common_dto_cardsource_PackageDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cn_mayu_yugioh_common_dto_cardsource_PackageDetail_descriptor,
        new java.lang.String[] { "PackageName", "OfferingDate", "CardCount", "Abbreviate", "PackageImg", "CoverImg", "Cards", });
    cn.mayu.yugioh.common.dto.transform.CardProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
