//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: limit_detil.proto
//
//package cn.mayu.yugioh.facade.sync.home;
//
//public final class LimitDetilProto {
//  private LimitDetilProto() {}
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//  }
//  public interface LimitDetilEntityOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:cn.mayu.yugioh.facade.sync.home.LimitDetilEntity)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>optional string name = 1;</code>
//     */
//    boolean hasName();
//    /**
//     * <code>optional string name = 1;</code>
//     */
//    java.lang.String getName();
//    /**
//     * <code>optional string name = 1;</code>
//     */
//    com.google.protobuf.ByteString
//        getNameBytes();
//
//    /**
//     * <code>optional int32 limitVal = 2;</code>
//     */
//    boolean hasLimitVal();
//    /**
//     * <code>optional int32 limitVal = 2;</code>
//     */
//    int getLimitVal();
//
//    /**
//     * <code>optional string cardName = 3;</code>
//     */
//    boolean hasCardName();
//    /**
//     * <code>optional string cardName = 3;</code>
//     */
//    java.lang.String getCardName();
//    /**
//     * <code>optional string cardName = 3;</code>
//     */
//    com.google.protobuf.ByteString
//        getCardNameBytes();
//
//    /**
//     * <code>optional string psw = 4;</code>
//     */
//    boolean hasPsw();
//    /**
//     * <code>optional string psw = 4;</code>
//     */
//    java.lang.String getPsw();
//    /**
//     * <code>optional string psw = 4;</code>
//     */
//    com.google.protobuf.ByteString
//        getPswBytes();
//
//    /**
//     * <code>optional int32 typeVal = 5;</code>
//     */
//    boolean hasTypeVal();
//    /**
//     * <code>optional int32 typeVal = 5;</code>
//     */
//    int getTypeVal();
//  }
//  /**
//   * Protobuf type {@code cn.mayu.yugioh.facade.sync.home.LimitDetilEntity}
//   */
//  public static final class LimitDetilEntity extends
//      com.google.protobuf.GeneratedMessage implements
//      // @@protoc_insertion_point(message_implements:cn.mayu.yugioh.facade.sync.home.LimitDetilEntity)
//      LimitDetilEntityOrBuilder {
//    // Use LimitDetilEntity.newBuilder() to construct.
//    private LimitDetilEntity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
//      super(builder);
//      this.unknownFields = builder.getUnknownFields();
//    }
//    private LimitDetilEntity(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }
//
//    private static final LimitDetilEntity defaultInstance;
//    public static LimitDetilEntity getDefaultInstance() {
//      return defaultInstance;
//    }
//
//    public LimitDetilEntity getDefaultInstanceForType() {
//      return defaultInstance;
//    }
//
//    private final com.google.protobuf.UnknownFieldSet unknownFields;
//    @java.lang.Override
//    public final com.google.protobuf.UnknownFieldSet
//        getUnknownFields() {
//      return this.unknownFields;
//    }
//    private LimitDetilEntity(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      initFields();
//      //int mutable_bitField0_ = 0;
//      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
//          com.google.protobuf.UnknownFieldSet.newBuilder();
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            default: {
//              if (!parseUnknownField(input, unknownFields,
//                                     extensionRegistry, tag)) {
//                done = true;
//              }
//              break;
//            }
//            case 10: {
//              com.google.protobuf.ByteString bs = input.readBytes();
//              bitField0_ |= 0x00000001;
//              name_ = bs;
//              break;
//            }
//            case 16: {
//              bitField0_ |= 0x00000002;
//              limitVal_ = input.readInt32();
//              break;
//            }
//            case 26: {
//              com.google.protobuf.ByteString bs = input.readBytes();
//              bitField0_ |= 0x00000004;
//              cardName_ = bs;
//              break;
//            }
//            case 34: {
//              com.google.protobuf.ByteString bs = input.readBytes();
//              bitField0_ |= 0x00000008;
//              psw_ = bs;
//              break;
//            }
//            case 40: {
//              bitField0_ |= 0x00000010;
//              typeVal_ = input.readInt32();
//              break;
//            }
//          }
//        }
//      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new com.google.protobuf.InvalidProtocolBufferException(
//            e.getMessage()).setUnfinishedMessage(this);
//      } finally {
//        this.unknownFields = unknownFields.build();
//        makeExtensionsImmutable();
//      }
//    }
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return cn.mayu.yugioh.facade.sync.home.LimitDetilProto.internal_static_cn_mayu_yugioh_facade_sync_home_LimitDetilEntity_descriptor;
//    }
//
//    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return cn.mayu.yugioh.facade.sync.home.LimitDetilProto.internal_static_cn_mayu_yugioh_facade_sync_home_LimitDetilEntity_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity.class, cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity.Builder.class);
//    }
//
//    public static com.google.protobuf.Parser<LimitDetilEntity> PARSER =
//        new com.google.protobuf.AbstractParser<LimitDetilEntity>() {
//      public LimitDetilEntity parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return new LimitDetilEntity(input, extensionRegistry);
//      }
//    };
//
//    @java.lang.Override
//    public com.google.protobuf.Parser<LimitDetilEntity> getParserForType() {
//      return PARSER;
//    }
//
//    private int bitField0_;
//    public static final int NAME_FIELD_NUMBER = 1;
//    private java.lang.Object name_;
//    /**
//     * <code>optional string name = 1;</code>
//     */
//    public boolean hasName() {
//      return ((bitField0_ & 0x00000001) == 0x00000001);
//    }
//    /**
//     * <code>optional string name = 1;</code>
//     */
//    public java.lang.String getName() {
//      java.lang.Object ref = name_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs = 
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          name_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>optional string name = 1;</code>
//     */
//    public com.google.protobuf.ByteString
//        getNameBytes() {
//      java.lang.Object ref = name_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b = 
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        name_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int LIMITVAL_FIELD_NUMBER = 2;
//    private int limitVal_;
//    /**
//     * <code>optional int32 limitVal = 2;</code>
//     */
//    public boolean hasLimitVal() {
//      return ((bitField0_ & 0x00000002) == 0x00000002);
//    }
//    /**
//     * <code>optional int32 limitVal = 2;</code>
//     */
//    public int getLimitVal() {
//      return limitVal_;
//    }
//
//    public static final int CARDNAME_FIELD_NUMBER = 3;
//    private java.lang.Object cardName_;
//    /**
//     * <code>optional string cardName = 3;</code>
//     */
//    public boolean hasCardName() {
//      return ((bitField0_ & 0x00000004) == 0x00000004);
//    }
//    /**
//     * <code>optional string cardName = 3;</code>
//     */
//    public java.lang.String getCardName() {
//      java.lang.Object ref = cardName_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs = 
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          cardName_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>optional string cardName = 3;</code>
//     */
//    public com.google.protobuf.ByteString
//        getCardNameBytes() {
//      java.lang.Object ref = cardName_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b = 
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        cardName_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int PSW_FIELD_NUMBER = 4;
//    private java.lang.Object psw_;
//    /**
//     * <code>optional string psw = 4;</code>
//     */
//    public boolean hasPsw() {
//      return ((bitField0_ & 0x00000008) == 0x00000008);
//    }
//    /**
//     * <code>optional string psw = 4;</code>
//     */
//    public java.lang.String getPsw() {
//      java.lang.Object ref = psw_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs = 
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          psw_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>optional string psw = 4;</code>
//     */
//    public com.google.protobuf.ByteString
//        getPswBytes() {
//      java.lang.Object ref = psw_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b = 
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        psw_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int TYPEVAL_FIELD_NUMBER = 5;
//    private int typeVal_;
//    /**
//     * <code>optional int32 typeVal = 5;</code>
//     */
//    public boolean hasTypeVal() {
//      return ((bitField0_ & 0x00000010) == 0x00000010);
//    }
//    /**
//     * <code>optional int32 typeVal = 5;</code>
//     */
//    public int getTypeVal() {
//      return typeVal_;
//    }
//
//    private void initFields() {
//      name_ = "";
//      limitVal_ = 0;
//      cardName_ = "";
//      psw_ = "";
//      typeVal_ = 0;
//    }
//    private byte memoizedIsInitialized = -1;
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      getSerializedSize();
//      if (((bitField0_ & 0x00000001) == 0x00000001)) {
//        output.writeBytes(1, getNameBytes());
//      }
//      if (((bitField0_ & 0x00000002) == 0x00000002)) {
//        output.writeInt32(2, limitVal_);
//      }
//      if (((bitField0_ & 0x00000004) == 0x00000004)) {
//        output.writeBytes(3, getCardNameBytes());
//      }
//      if (((bitField0_ & 0x00000008) == 0x00000008)) {
//        output.writeBytes(4, getPswBytes());
//      }
//      if (((bitField0_ & 0x00000010) == 0x00000010)) {
//        output.writeInt32(5, typeVal_);
//      }
//      getUnknownFields().writeTo(output);
//    }
//
//    private int memoizedSerializedSize = -1;
//    public int getSerializedSize() {
//      int size = memoizedSerializedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (((bitField0_ & 0x00000001) == 0x00000001)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeBytesSize(1, getNameBytes());
//      }
//      if (((bitField0_ & 0x00000002) == 0x00000002)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeInt32Size(2, limitVal_);
//      }
//      if (((bitField0_ & 0x00000004) == 0x00000004)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeBytesSize(3, getCardNameBytes());
//      }
//      if (((bitField0_ & 0x00000008) == 0x00000008)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeBytesSize(4, getPswBytes());
//      }
//      if (((bitField0_ & 0x00000010) == 0x00000010)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeInt32Size(5, typeVal_);
//      }
//      size += getUnknownFields().getSerializedSize();
//      memoizedSerializedSize = size;
//      return size;
//    }
//
//    private static final long serialVersionUID = 0L;
//    @java.lang.Override
//    protected java.lang.Object writeReplace()
//        throws java.io.ObjectStreamException {
//      return super.writeReplace();
//    }
//
//    public static cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return PARSER.parseFrom(input);
//    }
//    public static cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return PARSER.parseFrom(input, extensionRegistry);
//    }
//    public static cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return PARSER.parseDelimitedFrom(input);
//    }
//    public static cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return PARSER.parseDelimitedFrom(input, extensionRegistry);
//    }
//    public static cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return PARSER.parseFrom(input);
//    }
//    public static cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return PARSER.parseFrom(input, extensionRegistry);
//    }
//
//    public static Builder newBuilder() { return Builder.create(); }
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder(cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity prototype) {
//      return newBuilder().mergeFrom(prototype);
//    }
//    public Builder toBuilder() { return newBuilder(this); }
//
//    @java.lang.Override
//    protected Builder newBuilderForType(
//        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code cn.mayu.yugioh.facade.sync.home.LimitDetilEntity}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:cn.mayu.yugioh.facade.sync.home.LimitDetilEntity)
//        cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntityOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return cn.mayu.yugioh.facade.sync.home.LimitDetilProto.internal_static_cn_mayu_yugioh_facade_sync_home_LimitDetilEntity_descriptor;
//      }
//
//      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return cn.mayu.yugioh.facade.sync.home.LimitDetilProto.internal_static_cn_mayu_yugioh_facade_sync_home_LimitDetilEntity_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity.class, cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity.Builder.class);
//      }
//
//      // Construct using cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
//        }
//      }
//      private static Builder create() {
//        return new Builder();
//      }
//
//      public Builder clear() {
//        super.clear();
//        name_ = "";
//        bitField0_ = (bitField0_ & ~0x00000001);
//        limitVal_ = 0;
//        bitField0_ = (bitField0_ & ~0x00000002);
//        cardName_ = "";
//        bitField0_ = (bitField0_ & ~0x00000004);
//        psw_ = "";
//        bitField0_ = (bitField0_ & ~0x00000008);
//        typeVal_ = 0;
//        bitField0_ = (bitField0_ & ~0x00000010);
//        return this;
//      }
//
//      public Builder clone() {
//        return create().mergeFrom(buildPartial());
//      }
//
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return cn.mayu.yugioh.facade.sync.home.LimitDetilProto.internal_static_cn_mayu_yugioh_facade_sync_home_LimitDetilEntity_descriptor;
//      }
//
//      public cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity getDefaultInstanceForType() {
//        return cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity.getDefaultInstance();
//      }
//
//      public cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity build() {
//        cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      public cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity buildPartial() {
//        cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity result = new cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity(this);
//        int from_bitField0_ = bitField0_;
//        int to_bitField0_ = 0;
//        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
//          to_bitField0_ |= 0x00000001;
//        }
//        result.name_ = name_;
//        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
//          to_bitField0_ |= 0x00000002;
//        }
//        result.limitVal_ = limitVal_;
//        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
//          to_bitField0_ |= 0x00000004;
//        }
//        result.cardName_ = cardName_;
//        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
//          to_bitField0_ |= 0x00000008;
//        }
//        result.psw_ = psw_;
//        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
//          to_bitField0_ |= 0x00000010;
//        }
//        result.typeVal_ = typeVal_;
//        result.bitField0_ = to_bitField0_;
//        onBuilt();
//        return result;
//      }
//
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity) {
//          return mergeFrom((cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity other) {
//        if (other == cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity.getDefaultInstance()) return this;
//        if (other.hasName()) {
//          bitField0_ |= 0x00000001;
//          name_ = other.name_;
//          onChanged();
//        }
//        if (other.hasLimitVal()) {
//          setLimitVal(other.getLimitVal());
//        }
//        if (other.hasCardName()) {
//          bitField0_ |= 0x00000004;
//          cardName_ = other.cardName_;
//          onChanged();
//        }
//        if (other.hasPsw()) {
//          bitField0_ |= 0x00000008;
//          psw_ = other.psw_;
//          onChanged();
//        }
//        if (other.hasTypeVal()) {
//          setTypeVal(other.getTypeVal());
//        }
//        this.mergeUnknownFields(other.getUnknownFields());
//        return this;
//      }
//
//      public final boolean isInitialized() {
//        return true;
//      }
//
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          parsedMessage = (cn.mayu.yugioh.facade.sync.home.LimitDetilProto.LimitDetilEntity) e.getUnfinishedMessage();
//          throw e;
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//      private int bitField0_;
//
//      private java.lang.Object name_ = "";
//      /**
//       * <code>optional string name = 1;</code>
//       */
//      public boolean hasName() {
//        return ((bitField0_ & 0x00000001) == 0x00000001);
//      }
//      /**
//       * <code>optional string name = 1;</code>
//       */
//      public java.lang.String getName() {
//        java.lang.Object ref = name_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            name_ = s;
//          }
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>optional string name = 1;</code>
//       */
//      public com.google.protobuf.ByteString
//          getNameBytes() {
//        java.lang.Object ref = name_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b = 
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          name_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>optional string name = 1;</code>
//       */
//      public Builder setName(
//          java.lang.String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000001;
//        name_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string name = 1;</code>
//       */
//      public Builder clearName() {
//        bitField0_ = (bitField0_ & ~0x00000001);
//        name_ = getDefaultInstance().getName();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string name = 1;</code>
//       */
//      public Builder setNameBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000001;
//        name_ = value;
//        onChanged();
//        return this;
//      }
//
//      private int limitVal_ ;
//      /**
//       * <code>optional int32 limitVal = 2;</code>
//       */
//      public boolean hasLimitVal() {
//        return ((bitField0_ & 0x00000002) == 0x00000002);
//      }
//      /**
//       * <code>optional int32 limitVal = 2;</code>
//       */
//      public int getLimitVal() {
//        return limitVal_;
//      }
//      /**
//       * <code>optional int32 limitVal = 2;</code>
//       */
//      public Builder setLimitVal(int value) {
//        bitField0_ |= 0x00000002;
//        limitVal_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional int32 limitVal = 2;</code>
//       */
//      public Builder clearLimitVal() {
//        bitField0_ = (bitField0_ & ~0x00000002);
//        limitVal_ = 0;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object cardName_ = "";
//      /**
//       * <code>optional string cardName = 3;</code>
//       */
//      public boolean hasCardName() {
//        return ((bitField0_ & 0x00000004) == 0x00000004);
//      }
//      /**
//       * <code>optional string cardName = 3;</code>
//       */
//      public java.lang.String getCardName() {
//        java.lang.Object ref = cardName_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            cardName_ = s;
//          }
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>optional string cardName = 3;</code>
//       */
//      public com.google.protobuf.ByteString
//          getCardNameBytes() {
//        java.lang.Object ref = cardName_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b = 
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          cardName_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>optional string cardName = 3;</code>
//       */
//      public Builder setCardName(
//          java.lang.String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000004;
//        cardName_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string cardName = 3;</code>
//       */
//      public Builder clearCardName() {
//        bitField0_ = (bitField0_ & ~0x00000004);
//        cardName_ = getDefaultInstance().getCardName();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string cardName = 3;</code>
//       */
//      public Builder setCardNameBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000004;
//        cardName_ = value;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object psw_ = "";
//      /**
//       * <code>optional string psw = 4;</code>
//       */
//      public boolean hasPsw() {
//        return ((bitField0_ & 0x00000008) == 0x00000008);
//      }
//      /**
//       * <code>optional string psw = 4;</code>
//       */
//      public java.lang.String getPsw() {
//        java.lang.Object ref = psw_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            psw_ = s;
//          }
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>optional string psw = 4;</code>
//       */
//      public com.google.protobuf.ByteString
//          getPswBytes() {
//        java.lang.Object ref = psw_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b = 
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          psw_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>optional string psw = 4;</code>
//       */
//      public Builder setPsw(
//          java.lang.String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000008;
//        psw_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string psw = 4;</code>
//       */
//      public Builder clearPsw() {
//        bitField0_ = (bitField0_ & ~0x00000008);
//        psw_ = getDefaultInstance().getPsw();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string psw = 4;</code>
//       */
//      public Builder setPswBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000008;
//        psw_ = value;
//        onChanged();
//        return this;
//      }
//
//      private int typeVal_ ;
//      /**
//       * <code>optional int32 typeVal = 5;</code>
//       */
//      public boolean hasTypeVal() {
//        return ((bitField0_ & 0x00000010) == 0x00000010);
//      }
//      /**
//       * <code>optional int32 typeVal = 5;</code>
//       */
//      public int getTypeVal() {
//        return typeVal_;
//      }
//      /**
//       * <code>optional int32 typeVal = 5;</code>
//       */
//      public Builder setTypeVal(int value) {
//        bitField0_ |= 0x00000010;
//        typeVal_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional int32 typeVal = 5;</code>
//       */
//      public Builder clearTypeVal() {
//        bitField0_ = (bitField0_ & ~0x00000010);
//        typeVal_ = 0;
//        onChanged();
//        return this;
//      }
//
//      // @@protoc_insertion_point(builder_scope:cn.mayu.yugioh.facade.sync.home.LimitDetilEntity)
//    }
//
//    static {
//      defaultInstance = new LimitDetilEntity(true);
//      defaultInstance.initFields();
//    }
//
//    // @@protoc_insertion_point(class_scope:cn.mayu.yugioh.facade.sync.home.LimitDetilEntity)
//  }
//
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_cn_mayu_yugioh_facade_sync_home_LimitDetilEntity_descriptor;
//  private static
//    com.google.protobuf.GeneratedMessage.FieldAccessorTable
//      internal_static_cn_mayu_yugioh_facade_sync_home_LimitDetilEntity_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    java.lang.String[] descriptorData = {
//      "\n\021limit_detil.proto\022\037cn.mayu.yugioh.faca" +
//      "de.sync.home\"b\n\020LimitDetilEntity\022\014\n\004name" +
//      "\030\001 \001(\t\022\020\n\010limitVal\030\002 \001(\005\022\020\n\010cardName\030\003 \001" +
//      "(\t\022\013\n\003psw\030\004 \001(\t\022\017\n\007typeVal\030\005 \001(\005B\021B\017Limi" +
//      "tDetilProto"
//    };
//    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
//        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
//          public com.google.protobuf.ExtensionRegistry assignDescriptors(
//              com.google.protobuf.Descriptors.FileDescriptor root) {
//            descriptor = root;
//            return null;
//          }
//        };
//    com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//        }, assigner);
//    internal_static_cn_mayu_yugioh_facade_sync_home_LimitDetilEntity_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_cn_mayu_yugioh_facade_sync_home_LimitDetilEntity_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
//        internal_static_cn_mayu_yugioh_facade_sync_home_LimitDetilEntity_descriptor,
//        new java.lang.String[] { "Name", "LimitVal", "CardName", "Psw", "TypeVal", });
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
