# jdk 是一个已有的包含 jdk 的镜像
 FROM java:8
 
#  作者签名
 MAINTAINER yugioh
 
#  简化 jar 的名字路径 （#：表示注释掉）
 COPY yugioh-basic-registry-1.0.ba90a76-SNAPSHOT.jar /yugioh-basic-registry.jar
 
#  执行 java -jar 命令 （CMD：在启动容器时才执行此行。RUN：构建镜像时就执行此行）
 CMD java -jar /yugioh-basic-registry.jar
 
#  设置对外端口为 9000
 EXPOSE 9000
 
#docker run --name=nexus -p 7001:8081 -p 5000:5000 -d sonatype/nexus3